const postTypes = {
    GET_ALL: "GET_ALL",
    ADD_QUESTION: "ADD_QUESTION",
    REMOVE_QUESTION: "REMOVE_QUESTION",
    USER_QUESTIONS: "USER_QUESTIONS",
    TOPIC_QUESTIONS: "TOPIC_QUESTIONS",
    LIKE_UNLIKE_QUESTION: "LIKE_UNLIKE_QUESTION",
    ADD_DELETE_COMMENT: "ADD_DELETE_COMMENT",
  };
  
  export default postTypes;